// Base de données d'aliments pour recherche autocomplete
// Catégories: fruits_legumes, viandes, epicerie, laitages, boulangerie, boissons, hygiene

export const FOODS_DATABASE = [
  // Fruits & Légumes
  { name: 'Pommes', category: 'fruits_legumes', keywords: 'pomme fruit' },
  { name: 'Bananes', category: 'fruits_legumes', keywords: 'banane fruit' },
  { name: 'Oranges', category: 'fruits_legumes', keywords: 'orange agrume' },
  { name: 'Citrons', category: 'fruits_legumes', keywords: 'citron jaune' },
  { name: 'Fraises', category: 'fruits_legumes', keywords: 'fraise fruit rouge' },
  { name: 'Raisin', category: 'fruits_legumes', keywords: 'raisin fruit' },
  { name: 'Melon', category: 'fruits_legumes', keywords: 'melon pastèque' },
  { name: 'Pastèque', category: 'fruits_legumes', keywords: 'pastèque melon' },
  { name: 'Kiwis', category: 'fruits_legumes', keywords: 'kiwi fruit vert' },
  { name: 'Ananas', category: 'fruits_legumes', keywords: 'ananas fruit' },
  { name: 'Mangue', category: 'fruits_legumes', keywords: 'mangue fruit exotique' },
  { name: 'Pêches', category: 'fruits_legumes', keywords: 'pêche fruit' },
  { name: 'Abricots', category: 'fruits_legumes', keywords: 'abricot fruit' },
  { name: 'Cerises', category: 'fruits_legumes', keywords: 'cerise fruit rouge' },
  { name: 'Prunes', category: 'fruits_legumes', keywords: 'prune fruit violet' },
  { name: 'Poires', category: 'fruits_legumes', keywords: 'poire fruit' },
  { name: 'Carottes', category: 'fruits_legumes', keywords: 'carotte orange légume' },
  { name: 'Pommes de terre', category: 'fruits_legumes', keywords: 'patate pomme terre' },
  { name: 'Tomates', category: 'fruits_legumes', keywords: 'tomate rouge légume' },
  { name: 'Tomates cerises', category: 'fruits_legumes', keywords: 'tomate cerise' },
  { name: 'Concombres', category: 'fruits_legumes', keywords: 'concombre vert légume' },
  { name: 'Courgettes', category: 'fruits_legumes', keywords: 'courgette légume' },
  { name: 'Aubergines', category: 'fruits_legumes', keywords: 'aubergine violet légume' },
  { name: 'Poivrons', category: 'fruits_legumes', keywords: 'poivron légume' },
  { name: 'Oignons', category: 'fruits_legumes', keywords: 'oignon légume' },
  { name: 'Ail', category: 'fruits_legumes', keywords: 'ail gousse' },
  { name: 'Échalotes', category: 'fruits_legumes', keywords: 'échalote oignon' },
  { name: 'Poireaux', category: 'fruits_legumes', keywords: 'poireau vert légume' },
  { name: 'Céleri', category: 'fruits_legumes', keywords: 'céleri branche' },
  { name: 'Betteraves', category: 'fruits_legumes', keywords: 'betterave rouge' },
  { name: 'Brocolis', category: 'fruits_legumes', keywords: 'brocoli vert chou' },
  { name: 'Chou-fleur', category: 'fruits_legumes', keywords: 'chou fleur blanc' },
  { name: 'Chou', category: 'fruits_legumes', keywords: 'chou blanc rouge' },
  { name: 'Salade', category: 'fruits_legumes', keywords: 'salade verte laitue' },
  { name: 'Roquette', category: 'fruits_legumes', keywords: 'roquette salade' },
  { name: 'Épinards', category: 'fruits_legumes', keywords: 'épinard feuille vert' },
  { name: 'Asperges', category: 'fruits_legumes', keywords: 'asperge verte' },
  { name: 'Haricots verts', category: 'fruits_legumes', keywords: 'haricot vert' },
  { name: 'Petits pois', category: 'fruits_legumes', keywords: 'petit pois' },
  { name: 'Maïs', category: 'fruits_legumes', keywords: 'maïs' },
  { name: 'Champignons', category: 'fruits_legumes', keywords: 'champignon paris' },
  { name: 'Avocats', category: 'fruits_legumes', keywords: 'avocat fruit' },
  { name: 'Artichauts', category: 'fruits_legumes', keywords: 'artichaut' },
  { name: 'Fenouil', category: 'fruits_legumes', keywords: 'fenouil' },
  { name: 'Radis', category: 'fruits_legumes', keywords: 'radis rose' },
  { name: 'Navets', category: 'fruits_legumes', keywords: 'navet blanc' },
  { name: 'Courge', category: 'fruits_legumes', keywords: 'courge butternut' },
  { name: 'Potimarron', category: 'fruits_legumes', keywords: 'potimarron courge' },
  { name: 'Citrouille', category: 'fruits_legumes', keywords: 'citrouille' },
  { name: 'Pâtisson', category: 'fruits_legumes', keywords: 'pâtisson' },
  { name: 'Persil', category: 'fruits_legumes', keywords: 'persil herbe' },
  { name: 'Coriandre', category: 'fruits_legumes', keywords: 'coriandre herbe' },
  { name: 'Menthe', category: 'fruits_legumes', keywords: 'menthe herbe' },
  { name: 'Basilic', category: 'fruits_legumes', keywords: 'basilic herbe' },
  { name: 'Origan', category: 'fruits_legumes', keywords: 'origan herbe' },
  { name: 'Thym', category: 'fruits_legumes', keywords: 'thym herbe' },
  { name: 'Romarin', category: 'fruits_legumes', keywords: 'romarin herbe' },
  { name: 'Ciboulette', category: 'fruits_legumes', keywords: 'ciboulette herbe' },
  
  // Viandes & Poissons
  { name: 'Poulet', category: 'viandes', keywords: 'poulet volaille' },
  { name: 'Filets de poulet', category: 'viandes', keywords: 'poulet filet blanc' },
  { name: 'Cuisses de poulet', category: 'viandes', keywords: 'poulet cuisse' },
  { name: 'Dinde', category: 'viandes', keywords: 'dinde volaille' },
  { name: 'Canard', category: 'viandes', keywords: 'canard volaille' },
  { name: 'Magret de canard', category: 'viandes', keywords: 'canard magret' },
  { name: 'Lapin', category: 'viandes', keywords: 'lapin' },
  { name: 'Bœuf', category: 'viandes', keywords: 'bœuf viande' },
  { name: 'Steak haché', category: 'viandes', keywords: 'bœuf haché steak' },
  { name: 'Entrecôte', category: 'viandes', keywords: 'bœuf entrecôte' },
  { name: 'Faux-filet', category: 'viandes', keywords: 'bœuf faux-filet' },
  { name: 'Filet mignon', category: 'viandes', keywords: 'bœuf filet' },
  { name: 'Rumsteak', category: 'viandes', keywords: 'bœuf rumsteak' },
  { name: 'Côte de bœuf', category: 'viandes', keywords: 'bœuf côte' },
  { name: 'Onglet', category: 'viandes', keywords: 'bœuf onglet' },
  { name: 'Bavette', category: 'viandes', keywords: 'bœuf bavette' },
  { name: 'Veau', category: 'viandes', keywords: 'veau viande' },
  { name: 'Escalope de veau', category: 'viandes', keywords: 'veau escalope' },
  { name: 'Agneau', category: 'viandes', keywords: 'agneau' },
  { name: 'Gigot d\'agneau', category: 'viandes', keywords: 'agneau gigot' },
  { name: 'Côtelette d\'agneau', category: 'viandes', keywords: 'agneau côtelette' },
  { name: 'Porc', category: 'viandes', keywords: 'porc cochon' },
  { name: 'Côte de porc', category: 'viandes', keywords: 'porc côte' },
  { name: 'Filet mignon de porc', category: 'viandes', keywords: 'porc filet' },
  { name: 'Rôti de porc', category: 'viandes', keywords: 'porc rôti' },
  { name: 'Jambon', category: 'viandes', keywords: 'jambon blanc cuit' },
  { name: 'Jambon cru', category: 'viandes', keywords: 'jambon cru serrano' },
  { name: 'Lardons', category: 'viandes', keywords: 'lardon' },
  { name: 'Saucisse', category: 'viandes', keywords: 'saucisse porc' },
  { name: 'Saucisson sec', category: 'viandes', keywords: 'saucisson sec' },
  { name: 'Chorizo', category: 'viandes', keywords: 'chorizo épicé' },
  { name: 'Merguez', category: 'viandes', keywords: 'merguez épicé' },
  { name: 'Chipolatas', category: 'viandes', keywords: 'chipolata saucisse' },
  { name: 'Pâté', category: 'viandes', keywords: 'pâté' },
  { name: 'Rillettes', category: 'viandes', keywords: 'rillettes' },
  { name: 'Saumon', category: 'viandes', keywords: 'saumon poisson' },
  { name: 'Saumon fumé', category: 'viandes', keywords: 'saumon fumé' },
  { name: 'Cabillaud', category: 'viandes', keywords: 'cabillaud poisson blanc' },
  { name: 'Morue', category: 'viandes', keywords: 'morue poisson' },
  { name: 'Lieu noir', category: 'viandes', keywords: 'lieu poisson' },
  { name: 'Sole', category: 'viandes', keywords: 'sole poisson plat' },
  { name: 'Merlan', category: 'viandes', keywords: 'merlan poisson' },
  { name: 'Colin', category: 'viandes', keywords: 'colin poisson' },
  { name: 'Lieu jaune', category: 'viandes', keywords: 'lieu jaune poisson' },
  { name: 'Thon', category: 'viandes', keywords: 'thon poisson' },
  { name: 'Thon en boîte', category: 'viandes', keywords: 'thon conserve' },
  { name: 'Sardines', category: 'viandes', keywords: 'sardine poisson' },
  { name: 'Maquereau', category: 'viandes', keywords: 'maquereau poisson' },
  { name: 'Hareng', category: 'viandes', keywords: 'hareng poisson' },
  { name: 'Truite', category: 'viandes', keywords: 'truite poisson' },
  { name: 'Bar', category: 'viandes', keywords: 'bar poisson loup de mer' },
  { name: 'Daurade', category: 'viandes', keywords: 'daurade poisson dorade' },
  { name: 'Rouget', category: 'viandes', keywords: 'rouget poisson' },
  { name: 'Saint-jacques', category: 'viandes', keywords: 'saint jacques coquille' },
  { name: 'Moules', category: 'viandes', keywords: 'moule coquillage' },
  { name: 'Huîtres', category: 'viandes', keywords: 'huître coquillage' },
  { name: 'Crevettes', category: 'viandes', keywords: 'crevette crustacé' },
  { name: 'Crevettes roses', category: 'viandes', keywords: 'crevette rose' },
  { name: 'Gambas', category: 'viandes', keywords: 'gambas crevette' },
  { name: 'Langoustines', category: 'viandes', keywords: 'langoustine' },
  { name: 'Homard', category: 'viandes', keywords: 'homard crustacé' },
  { name: 'Tourteau', category: 'viandes', keywords: 'tourteau crabe' },
  { name: 'Crabe', category: 'viandes', keywords: 'crabe' },
  
  // Épicerie
  { name: 'Riz', category: 'epicerie', keywords: 'riz blanc' },
  { name: 'Riz basmati', category: 'epicerie', keywords: 'riz basmati' },
  { name: 'Riz complet', category: 'epicerie', keywords: 'riz complet brun' },
  { name: 'Pâtes', category: 'epicerie', keywords: 'pâte spaghetti' },
  { name: 'Spaghetti', category: 'epicerie', keywords: 'spaghetti pâte' },
  { name: 'Penne', category: 'epicerie', keywords: 'penne pâte' },
  { name: 'Fusilli', category: 'epicerie', keywords: 'fusilli pâte' },
  { name: 'Tagliatelle', category: 'epicerie', keywords: 'tagliatelle pâte' },
  { name: 'Lasagnes', category: 'epicerie', keywords: 'lasagne pâte' },
  { name: 'Couscous', category: 'epicerie', keywords: 'couscous semoule' },
  { name: 'Semoule', category: 'epicerie', keywords: 'semoule' },
  { name: 'Quinoa', category: 'epicerie', keywords: 'quinoa' },
  { name: 'Lentilles', category: 'epicerie', keywords: 'lentille' },
  { name: 'Pois chiches', category: 'epicerie', keywords: 'pois chiche' },
  { name: 'Haricots rouges', category: 'epicerie', keywords: 'haricot rouge' },
  { name: 'Pain', category: 'boulangerie', keywords: 'pain baguette' },
  { name: 'Baguette', category: 'boulangerie', keywords: 'baguette pain' },
  { name: 'Pain de mie', category: 'boulangerie', keywords: 'pain mie' },
  { name: 'Pain complet', category: 'boulangerie', keywords: 'pain complet' },
  { name: 'Croissants', category: 'boulangerie', keywords: 'croissant viennoiserie' },
  { name: 'Pains au chocolat', category: 'boulangerie', keywords: 'pain chocolat' },
  { name: 'Brioche', category: 'boulangerie', keywords: 'brioche' },
  { name: 'Farine', category: 'epicerie', keywords: 'farine blanche' },
  { name: 'Sucre', category: 'epicerie', keywords: 'sucre blanc' },
  { name: 'Sucre roux', category: 'epicerie', keywords: 'sucre roux' },
  { name: 'Miel', category: 'epicerie', keywords: 'miel' },
  { name: 'Confiture', category: 'epicerie', keywords: 'confiture fraise' },
  { name: 'Nutella', category: 'epicerie', keywords: 'nutella chocolat' },
  { name: 'Huile d\'olive', category: 'epicerie', keywords: 'huile olive' },
  { name: 'Huile de tournesol', category: 'epicerie', keywords: 'huile tournesol' },
  { name: 'Vinaigre', category: 'epicerie', keywords: 'vinaigre balsamique' },
  { name: 'Moutarde', category: 'epicerie', keywords: 'moutarde' },
  { name: 'Ketchup', category: 'epicerie', keywords: 'ketchup' },
  { name: 'Mayonnaise', category: 'epicerie', keywords: 'mayonnaise' },
  { name: 'Sauce tomate', category: 'epicerie', keywords: 'sauce tomate' },
  { name: 'Sauce soja', category: 'epicerie', keywords: 'sauce soja' },
  { name: 'Sauce pesto', category: 'epicerie', keywords: 'sauce pesto' },
  { name: 'Café', category: 'epicerie', keywords: 'café moulu' },
  { name: 'Thé', category: 'epicerie', keywords: 'thé noir vert' },
  { name: 'Chocolat en poudre', category: 'epicerie', keywords: 'chocolat poudre' },
  { name: 'Cacao', category: 'epicerie', keywords: 'cacao poudre' },
  { name: 'Chocolat noir', category: 'epicerie', keywords: 'chocolat noir dessert' },
  { name: 'Chocolat au lait', category: 'epicerie', keywords: 'chocolat lait' },
  { name: 'Biscuits', category: 'epicerie', keywords: 'biscuit gâteau sec' },
  { name: 'Gâteaux apéritifs', category: 'epicerie', keywords: 'gâteau apéritif chips' },
  { name: 'Chips', category: 'epicerie', keywords: 'chips pomme terre' },
  { name: 'Noix', category: 'fruits_legumes', keywords: 'noix fruit sec' },
  { name: 'Amandes', category: 'fruits_legumes', keywords: 'amande fruit sec' },
  { name: 'Noisettes', category: 'fruits_legumes', keywords: 'noisette fruit sec' },
  { name: 'Raisins secs', category: 'fruits_legumes', keywords: 'raisin sec' },
  { name: 'Abricots secs', category: 'fruits_legumes', keywords: 'abricot sec' },
  { name: 'Dattes', category: 'fruits_legumes', keywords: 'date fruit sec' },
  
  // Laitages
  { name: 'Lait', category: 'laitages', keywords: 'lait entier demi-écrémé' },
  { name: 'Lait demi-écrémé', category: 'laitages', keywords: 'lait demi-écrémé' },
  { name: 'Lait écrémé', category: 'laitages', keywords: 'lait écrémé' },
  { name: 'Crème fraîche', category: 'laitages', keywords: 'crème fraîche' },
  { name: 'Yaourt', category: 'laitages', keywords: 'yaourt nature' },
  { name: 'Yaourt nature', category: 'laitages', keywords: 'yaourt nature' },
  { name: 'Yaourt aux fruits', category: 'laitages', keywords: 'yaourt fruit' },
  { name: 'Fromage blanc', category: 'laitages', keywords: 'fromage blanc' },
  { name: 'Œufs', category: 'laitages', keywords: 'œuf poule' },
  { name: 'Beurre', category: 'laitages', keywords: 'beurre doux' },
  { name: 'Fromage râpé', category: 'laitages', keywords: 'fromage râpé' },
  { name: 'Emmental', category: 'laitages', keywords: 'emmental fromage' },
  { name: 'Comté', category: 'laitages', keywords: 'comté fromage' },
  { name: 'Camembert', category: 'laitages', keywords: 'camembert fromage' },
  { name: 'Brie', category: 'laitages', keywords: 'brie fromage' },
  { name: 'Roquefort', category: 'laitages', keywords: 'roquefort fromage' },
  { name: 'Chèvre', category: 'laitages', keywords: 'fromage chèvre' },
  { name: 'Mozzarella', category: 'laitages', keywords: 'mozzarella fromage' },
  { name: 'Parmesan', category: 'laitages', keywords: 'parmesan fromage' },
  { name: 'Feta', category: 'laitages', keywords: 'feta fromage' },
  { name: 'Mascarpone', category: 'laitages', keywords: 'mascarpone fromage' },
  { name: 'Ricotta', category: 'laitages', keywords: 'ricotta fromage' },
  
  // Boissons
  { name: 'Eau', category: 'boissons', keywords: 'eau minérale plate' },
  { name: 'Eau gazeuse', category: 'boissons', keywords: 'eau gazeuse pétillante' },
  { name: 'Coca-Cola', category: 'boissons', keywords: 'coca soda' },
  { name: 'Coca-Cola Zero', category: 'boissons', keywords: 'coca zero' },
  { name: 'Orangina', category: 'boissons', keywords: 'orangina soda' },
  { name: 'Schweppes', category: 'boissons', keywords: 'schweppes tonic' },
  { name: 'Jus d\'orange', category: 'boissons', keywords: 'jus orange' },
  { name: 'Jus de pomme', category: 'boissons', keywords: 'jus pomme' },
  { name: 'Jus multifruit', category: 'boissons', keywords: 'jus multifruit' },
  { name: 'Smoothie', category: 'boissons', keywords: 'smoothie fruit' },
  { name: 'Limonade', category: 'boissons', keywords: 'limonade' },
  { name: 'Tonic', category: 'boissons', keywords: 'eau tonic' },
  
  // Hygiène
  { name: 'Papier toilette', category: 'hygiene', keywords: 'papier toilette wc' },
  { name: 'Essuie-tout', category: 'hygiene', keywords: 'essuie-tout sopalin' },
  { name: 'Mouchoirs', category: 'hygiene', keywords: 'mouchoir papier' },
  { name: 'Shampooing', category: 'hygiene', keywords: 'shampooing cheveux' },
  { name: 'Gel douche', category: 'hygiene', keywords: 'gel douche savon' },
  { name: 'Savon', category: 'hygiene', keywords: 'savon main' },
  { name: 'Dentifrice', category: 'hygiene', keywords: 'dentifrice dents' },
  { name: 'Brosse à dents', category: 'hygiene', keywords: 'brosse dent' },
  { name: 'Déodorant', category: 'hygiene', keywords: 'déodorant' },
  { name: 'Rasoir', category: 'hygiene', keywords: 'rasoir lame' },
  { name: 'Lessive', category: 'hygiene', keywords: 'lessive machine' },
  { name: 'Adoucissant', category: 'hygiene', keywords: 'adoucissant lessive' },
  { name: 'Liquide vaisselle', category: 'hygiene', keywords: 'vaisselle liquide' },
  { name: 'Éponges', category: 'hygiene', keywords: 'éponge vaisselle' },
  { name: 'Sac poubelle', category: 'hygiene', keywords: 'sac poubelle' },
  { name: 'Produit ménager', category: 'hygiene', keywords: 'produit ménager nettoyant' },
  { name: 'Nettoyant multi-usages', category: 'hygiene', keywords: 'nettoyant multi-usages' },
  { name: 'Vinaigre blanc', category: 'hygiene', keywords: 'vinaigre blanc ménager' },
  { name: 'Bicarbonate', category: 'hygiene', keywords: 'bicarbonate soude' },
  
  // Autre
  { name: 'Sel', category: 'epicerie', keywords: 'sel fin gros' },
  { name: 'Poivre', category: 'epicerie', keywords: 'poivre noir moulin' },
  { name: 'Herbes de Provence', category: 'epicerie', keywords: 'herbe provence' },
  { name: 'Curry', category: 'epicerie', keywords: 'curry poudre' },
  { name: 'Paprika', category: 'epicerie', keywords: 'paprika poudre' },
  { name: 'Cumin', category: 'epicerie', keywords: 'cumin grain poudre' },
  { name: 'Cannelle', category: 'epicerie', keywords: 'cannelle poudre' },
  { name: 'Vanille', category: 'epicerie', keywords: 'vanille gousse extrait' },
  { name: 'Gingembre', category: 'epicerie', keywords: 'gingembre frais poudre' },
  { name: 'Ail en poudre', category: 'epicerie', keywords: 'ail poudre' },
  { name: 'Bouillon cube', category: 'epicerie', keywords: 'bouillon cube poule bœuf légume' },
  { name: 'Levure chimique', category: 'epicerie', keywords: 'levure chimique poudre à pâte' },
  { name: 'Levure de boulanger', category: 'epicerie', keywords: 'levure boulange fraîche sèche' },
  { name: 'Sopalin', category: 'hygiene', keywords: 'sopalin essuie-tout' },
  { name: 'Film alimentaire', category: 'hygiene', keywords: 'film alimentaire transparent' },
  { name: 'Papier aluminium', category: 'hygiene', keywords: 'papier aluminium alu' },
  { name: 'Sacs de congélation', category: 'hygiene', keywords: 'sac congélation congélateur' },
  { name: 'Charbon de bois', category: 'autre', keywords: 'charbon bois barbecue' },
  { name: 'Allume-feu', category: 'autre', keywords: 'allume feu barbecue' },
  { name: 'Glace', category: 'autre', keywords: 'glace glaçon' },
]
