const weekly = (name, category) => ({ name, category, frequency: 'weekly' })
const biweekly = (name, category) => ({ name, category, frequency: 'biweekly' })
const monthly = (name, category) => ({ name, category, frequency: 'monthly' })
const daily = (name, category) => ({ name, category, frequency: 'daily' })

const onDays = (name, category, days) => ({
  name,
  category,
  frequency: 'weekly',
  interval: { type: 'days_of_week', days },
})

const everyMonths = (name, category, months) => ({
  name,
  category,
  frequency: 'monthly',
  interval: { type: 'month_interval', months },
})

export const HOUSEHOLD_TASKS = [
  weekly('Enlever la poussière', 'chambre'),
  weekly('Aspirer le sol', 'chambre'),
  weekly('Nettoyer sous le lit', 'chambre'),
  weekly('Nettoyer les tables de chevet', 'chambre'),
  biweekly('Changer les draps', 'chambre'),
  monthly('Ranger la garde-robe', 'chambre'),
  monthly('Rangement global', 'chambre'),
  monthly('Nettoyer les interrupteurs et prises', 'chambre'),
  monthly('Nettoyer les plinthes', 'chambre'),
  monthly('Nettoyer sous le canapé', 'chambre'),
  everyMonths('Nettoyer les fenêtres', 'chambre', 6),
  everyMonths('Laver les rideaux', 'chambre', 6),
  everyMonths('Laver les oreillers et couette', 'chambre', 6),

  daily("Laver l'évier", 'cuisine'),
  daily('Aspirer le sol', 'cuisine'),
  onDays('Laver la cuisinière', 'cuisine', [2, 4]),
  weekly('Retirer la poussière', 'cuisine'),
  weekly('Laver le four (extérieur)', 'cuisine'),
  weekly('Laver le micro-ondes', 'cuisine'),
  weekly('Laver le réfrigérateur (extérieur)', 'cuisine'),
  biweekly('Laver la machine à café', 'cuisine'),
  monthly('Ranger/Trier les placards', 'cuisine'),
  monthly('Rangement global', 'cuisine'),
  monthly("Nettoyer l'interrupteur", 'cuisine'),
  monthly('Nettoyer les interrupteurs et prises', 'cuisine'),
  monthly('Nettoyer les plinthes', 'cuisine'),
  monthly('Laver les plinthes', 'cuisine'),
  monthly('Laver les interrupteurs et prises', 'cuisine'),
  everyMonths('Nettoyer les fenêtres', 'cuisine', 2),
  everyMonths('Ranger les meubles', 'cuisine', 2),
  everyMonths('Laver le four (intérieur)', 'cuisine', 6),
  everyMonths('Laver le réfrigérateur (intérieur)', 'cuisine', 6),
  everyMonths('Laver le congélateur', 'cuisine', 6),
  everyMonths('Nettoyer le canapé', 'cuisine', 12),

  onDays('Aspirer le sol', 'salon', [2, 4]),
  weekly('Retirer la poussière', 'salon'),
  weekly('Vider la poubelle', 'salon'),
  weekly("Nettoyer la poignée et l'interrupteur", 'salon'),
  weekly('Ranger le canapé', 'salon'),
  monthly('Nettoyer les plinthes', 'salon'),
  monthly('Nettoyer sous le canapé', 'salon'),
  monthly("Nettoyer l'interrupteur", 'salon'),
  monthly('Nettoyer les interrupteurs et prises', 'salon'),
  monthly('Arroser les plantes', 'salon'),
  monthly('Ranger les meubles', 'salon'),
  monthly('Rangement global', 'salon'),
  monthly('Nettoyer la télévision', 'salon'),
  everyMonths('Laver la colonne', 'salon', 2),
  everyMonths('Nettoyer le dessus du meuble', 'salon', 2),
  everyMonths('Nettoyer les fenêtres', 'salon', 2),
  everyMonths('Nettoyer la machine à laver', 'salon', 4),

  weekly('Nettoyer le bain (rapide)', 'salle_de_bain'),
  weekly('Retirer la poussière', 'salle_de_bain'),
  weekly('Aspirer le sol', 'salle_de_bain'),
  weekly('Nettoyer les toilettes', 'salle_de_bain'),
  weekly('Vider la poubelle', 'salle_de_bain'),
  weekly('Remplacer les serviettes', 'salle_de_bain'),
  weekly("Nettoyer l'évier", 'salle_de_bain'),
  monthly('Nettoyer le bain (en profondeur)', 'salle_de_bain'),
  biweekly('Remplacer les tapis de bain', 'salle_de_bain'),
  biweekly('Nettoyer la brosse à toilettes', 'salle_de_bain'),
  biweekly('Ranger le meuble', 'salle_de_bain'),
  biweekly('Laver la machine à café', 'salle_de_bain'),
  everyMonths('Nettoyer les fenêtres', 'salle_de_bain', 6),
  everyMonths('Laver les rideaux', 'salle_de_bain', 6),
]
